services:
  - type: web
    name: mcp-cloud-server-nightcool
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 8080
      - key: TOKEN
        value: secret123