services:
  - type: web
    name: mcp-cloud-server-1
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 8080
      - key: TOKEN
        value: secret123
      - key: OPENAI_API_KEY
        sync: false  # Render Dashboard'dan manuel olarak eklenecek